/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupRecruiterRouteImport } from './routes/signup.recruiter'
import { Route as SignupEmployeeRouteImport } from './routes/signup.employee'
import { Route as AuthenticatedRecruiterRouteImport } from './routes/_authenticated/recruiter'
import { Route as AuthenticatedEmployeeRouteImport } from './routes/_authenticated/employee'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRecruiterRoute = SignupRecruiterRouteImport.update({
  id: '/signup/recruiter',
  path: '/signup/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupEmployeeRoute = SignupEmployeeRouteImport.update({
  id: '/signup/employee',
  path: '/signup/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecruiterRoute = AuthenticatedRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployeeRoute = AuthenticatedEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/recruiter': typeof AuthenticatedRecruiterRoute
  '/signup/employee': typeof SignupEmployeeRoute
  '/signup/recruiter': typeof SignupRecruiterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/recruiter': typeof AuthenticatedRecruiterRoute
  '/signup/employee': typeof SignupEmployeeRoute
  '/signup/recruiter': typeof SignupRecruiterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/_authenticated/employee': typeof AuthenticatedEmployeeRoute
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRoute
  '/signup/employee': typeof SignupEmployeeRoute
  '/signup/recruiter': typeof SignupRecruiterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/login'
    | '/employee'
    | '/recruiter'
    | '/signup/employee'
    | '/signup/recruiter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/login'
    | '/employee'
    | '/recruiter'
    | '/signup/employee'
    | '/signup/recruiter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/faq'
    | '/login'
    | '/_authenticated/employee'
    | '/_authenticated/recruiter'
    | '/signup/employee'
    | '/signup/recruiter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  SignupEmployeeRoute: typeof SignupEmployeeRoute
  SignupRecruiterRoute: typeof SignupRecruiterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/recruiter': {
      id: '/signup/recruiter'
      path: '/signup/recruiter'
      fullPath: '/signup/recruiter'
      preLoaderRoute: typeof SignupRecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/employee': {
      id: '/signup/employee'
      path: '/signup/employee'
      fullPath: '/signup/employee'
      preLoaderRoute: typeof SignupEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employee': {
      id: '/_authenticated/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEmployeeRoute: typeof AuthenticatedEmployeeRoute
  AuthenticatedRecruiterRoute: typeof AuthenticatedRecruiterRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEmployeeRoute: AuthenticatedEmployeeRoute,
  AuthenticatedRecruiterRoute: AuthenticatedRecruiterRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  SignupEmployeeRoute: SignupEmployeeRoute,
  SignupRecruiterRoute: SignupRecruiterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
