// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqlvejwkkktxkwykpawl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxbHZlandra2t0eGt3eWtwYXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2OTMzNjIsImV4cCI6MjA5NDI2OTM2Mn0.Vm__jtHIdMtE-BjZ0Zc6n3w9nXX0fhWr53AObSmaZSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});